import {decodeURL,eventURL} from './event-codec';
import {validateEvent,validatePoint,type EventData,type Point,limits} from './event-validation';
import {localToUTC,localParts,formatEventDate} from './event-time';
import {mountFlipCountdown} from './flipclock-renderer';
import {mountCelebration} from './celebration';
import {nextOccasionDate} from './fixed-occasions';
import {copyText,nativeShare,invitation} from './share';
import {downloadCalendar} from './calendar-export';
import {renderMap,searchLocation} from './event-map';
import {directionsURL,currentPosition} from './directions';
import {loadAd,testAdAdapter} from './ads';
import {metrics} from './metrics';
import {localizedThemes} from '../i18n/themes';
import {translate as tr,currentLocale,localizedPath} from '../i18n/index';
import {restoreLanguageDraft} from './language-switch';
import {readableAccent} from './theme-colors';
import {fontFace,fontFamily} from '../data/fonts';
const base=import.meta.env.BASE_URL;const production=import.meta.env.PUBLIC_SITE_ORIGIN || 'https://contagem.vivace-softwares.com.br';const emit=metrics();
const pageURL=(slug:string)=>new URL(localizedPath(`${base}${slug}/`,currentLocale(),base),location.origin).href;
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const setText=(id:string,value:string)=>{const el=$(id);el.textContent=['basic-time-note','calendar-duration','action-status','copy-status','address-copy-status','decode-error','directions-status'].includes(id)?tr(value):value;el.hidden=!value;};
export function initEventApp(){restoreLanguageDraft();const themes=localizedThemes(currentLocale());const app=$('event-app');if(!app)return;app.hidden=false;const form=$<HTMLFormElement>('event-form');const value=(name:string)=>(form.elements.namedItem(name) as HTMLInputElement).value;const set=(name:string,text:string)=>(form.elements.namedItem(name) as HTMLInputElement).value=text;let slug=app.dataset.theme!;let confirmed:Point|undefined;let active:EventData|undefined;let activeURL='';let copyEpoch=0;let viewEpoch=0;let searchEpoch=0;let pendingPopup:Window|null=null;let lastOpenedURL='';let lastRenderKey='';let transientPoint:Point|undefined;let disposeClock:()=>void=()=>{};let disposeEffects:()=>void=()=>{};let formMode:'simple'|'complete'='simple';const browserZone=Intl.DateTimeFormat().resolvedOptions().timeZone||'America/Sao_Paulo';let disposeMap:()=>void=()=>{};let disposeCreatorMap:()=>void=()=>{};let observer:IntersectionObserver|undefined;
 const errors=(error:unknown)=>{const el=$('form-errors');form.querySelectorAll('input,textarea,select').forEach(field=>field.setAttribute('aria-describedby','form-errors'));el.hidden=false;el.textContent=tr((error as Error).message);el.focus();};
 const clearErrors=()=>{$('form-errors').hidden=true;form.querySelectorAll('[aria-describedby]').forEach(field=>field.removeAttribute('aria-describedby'));};
 function clearCreatorMap(){disposeCreatorMap();disposeCreatorMap=()=>{};$('creator-map').replaceChildren();$('creator-map').hidden=true;}function invalidateView(){viewEpoch++;searchEpoch++;$('location-results').replaceChildren();pendingPopup?.close();pendingPopup=null;clearCreatorMap();}function updateFields(){for(const name of Object.keys(limits) as (keyof typeof limits)[]){const counter=form.querySelector(`[data-count="${name}"]`);if(counter)counter.textContent=`${[...value(name).trim().normalize('NFC')].length} / ${limits[name]}`;}const hasLocal=Boolean(value('venue').trim()||value('address').trim());$('location-controls').hidden=!hasLocal;if(!hasLocal){confirmed=undefined;set('lat','');set('lon','');clearCreatorMap();} $('location-status').textContent=tr(confirmed?`Ponto confirmado: ${confirmed.lat}, ${confirmed.lon}`:'Ponto não confirmado.');}
 function setMode(mode:'simple'|'complete'){formMode=mode;app.querySelectorAll<HTMLElement>('[data-full]').forEach(field=>field.hidden=mode==='simple');$('simple-mode').setAttribute('aria-pressed',String(mode==='simple'));$('complete-mode').setAttribute('aria-pressed',String(mode==='complete'));setText('basic-time-note',mode==='simple'?`Data à meia-noite (00:00), no fuso ${browserZone}. Para escolher horário e detalhes, use Completo. Ao conferir a prévia ou gerar o link no modo Simples, os detalhes avançados serão descartados.`:'Horário, fuso e detalhes ficam no link. Compartilhe somente o que deseja tornar público.');}function suggestDate(){const suggested=nextOccasionDate(slug,formMode==='simple'?browserZone:value('timeZone'));if(suggested){set('date',suggested);set('time','00:00');}}
 function pointFromInputs(){if(!value('lat').trim()||!value('lon').trim())throw new Error('Informe latitude e longitude, ou marque no mapa.');return validatePoint({lat:Number(value('lat')),lon:Number(value('lon'))});}
 function readEvent():EventData {if(formMode==='simple')return validateEvent({title:value('title'),message:'',timeZone:browserZone,endAt:localToUTC(`${value('date')}T00:00`,browserZone)},true);const data:Record<string,unknown>={title:value('title'),message:value('message'),timeZone:value('timeZone'),endAt:localToUTC(`${value('date')}T${value('time')}`,value('timeZone'))};for(const name of ['organizer','venue','address','meetingUrl'])if(value(name).trim())data[name]=value(name);if(value('endDate')||value('endTime'))data.calendarEndsAt=localToUTC(`${value('endDate')}T${value('endTime')}`,value('timeZone'));if(confirmed)data.location=confirmed;return validateEvent(data,true);}
 function discardAdvanced(){if(formMode!=='simple')return;for(const name of ['message','organizer','venue','address','meetingUrl','endDate','endTime','lat','lon'])set(name,'');set('time','00:00');set('timeZone',browserZone);confirmed=undefined;clearCreatorMap();updateFields();}
 function fill(e:EventData,themeSlug:string){clearCreatorMap();setMode('complete');clearErrors();for(const name of ['title','message','timeZone','organizer','venue','address','meetingUrl'] as const)set(name,e[name]??'');const local=localParts(Date.parse(e.endAt),e.timeZone);set('date',local.slice(0,10));set('time',local.slice(11,16));const end=e.calendarEndsAt?localParts(Date.parse(e.calendarEndsAt),e.timeZone):'';set('endDate',end.slice(0,10));set('endTime',end.slice(11,16));confirmed=e.location;set('lat',e.location?String(e.location.lat):'');set('lon',e.location?String(e.location.lon):'');set('theme',themeSlug);slug=themeSlug;applyTheme();showCreator();updateFields();}
 type UI='simples'|'completo'|'editar'|'previa'|'erro';
 const names=['title','date','time','timeZone','theme','message','organizer','venue','address','meetingUrl','endDate','endTime','lat','lon','mapZoom'];
 const draft=()=>({values:Object.fromEntries(names.map(name=>[name,value(name)])),mode:formMode,confirmed});
 function restoreDraft(saved:ReturnType<typeof draft>){for(const name of names)if(typeof saved.values?.[name]==='string')set(name,saved.values[name]!);if(themes.some(t=>t.slug===value('theme')))slug=value('theme');confirmed=saved.confirmed;setMode(saved.mode==='complete'?'complete':'simple');applyTheme();updateFields();}
 function uiURL(ui:UI,event?:EventData){const url=new URL(event?eventURL(event,pageURL(slug)):pageURL(slug));url.searchParams.set('ui',ui);return url;}
 function saveDraft(){if($('creator').hidden)return;const url=new URL(location.href);if(!url.search)url.searchParams.set('ui',formMode==='simple'?'simples':'completo');try{url.hash=new URL(eventURL(readEvent(),pageURL(slug))).hash;}catch{/* An incomplete draft remains in this history entry, never in an event payload. */}history.replaceState({draft:draft()},'',url.pathname+url.search+url.hash);}
 function creatorState(ui:'simples'|'completo'|'editar',event?:EventData){const url=uiURL(ui,event);history.pushState({draft:draft()},'',url.pathname+url.search+url.hash);showCreator();}
 function changeMode(mode:'simple'|'complete'){saveDraft();setMode(mode);let event:EventData|undefined;try{event=readEvent();}catch{}creatorState(mode==='simple'?'simples':'completo',event);}
 function applyTheme(){const t=themes.find(t=>t.slug===slug)!;const face=$('theme-font-face');if(face)face.textContent=t.font==='Inter'?'':fontFace(t.font,base);document.documentElement.style.setProperty('--heading-font',fontFamily(t.font));app.style.setProperty('--event-accent',t.colors.accent);app.style.setProperty('--event-ink',readableAccent(t.colors.accent));app.style.setProperty('--event-soft',t.colors.soft);app.dataset.selectedTheme=slug;app.classList.toggle('dark-art',['ano-novo','formatura-ensino-medio','evento-tecnologia','festa','jantar'].includes(slug));app.style.setProperty('--event-background',['ano-novo','formatura-ensino-medio','evento-tecnologia','festa','jantar'].includes(slug)?'#1c2032':t.colors.background);app.style.setProperty('--event-art',`url("${base}${t.assets.desktop}")`);app.style.setProperty('--event-art-mobile',`url("${base}${t.assets.mobile}")`);document.title=`${t.name} | Contagem`;const intro=document.querySelector('.theme-intro');if(intro)intro.textContent=t.description;const about=$('theme-about');if(about)about.textContent=tr(`Crie um evento com o tema ${t.name.toLowerCase()}, escolha título e data, confira a prévia e compartilhe o link. O modo Completo permite horário, fuso e detalhes. Qualquer pessoa pode duplicar sem modificar o original.`);const heading=$('theme-title');if(heading)heading.textContent=t.name;const inspiration=$<HTMLImageElement>('creator-art');if(inspiration)inspiration.src=`${base}${t.assets.mobile}`;setText('creator-theme-name',t.name);const hero=document.querySelector<HTMLImageElement>('.theme-art img');if(hero)hero.src=`${base}${t.assets.desktop}`;const source=document.querySelector<HTMLSourceElement>('.theme-art source');if(source)source.srcset=`${base}${t.assets.mobile}`;}
 function showCreator(){invalidateView();setText('address-copy-status','');$('address-manual-copy').hidden=true;lastRenderKey='';copyEpoch++;setText('copy-status','');$('copy-link').textContent=tr('Copiar link');$('manual-copy').hidden=true;disposeEffects();const ad=app.querySelector<HTMLElement>('.ad-slot');if(ad)void loadAd(ad,'creator');document.querySelector('.theme-page')?.classList.remove('viewing-event');document.querySelector('.theme-page')?.classList.remove('viewing-error');disposeClock();disposeMap();observer?.disconnect();$('creator').hidden=false;$('event-view').hidden=true;$('event-error').hidden=true;$('creator-title').focus();}
 function configureDirections(p:Point){transientPoint=p;const a=$<HTMLAnchorElement>('manual-origin');a.href=directionsURL(p);$('directions').hidden=false;}
 function showMap(p:Point){const root=$('display-map');root.hidden=false;disposeMap();observer?.disconnect();const mount=()=>{disposeMap=renderMap(root,p);};if('IntersectionObserver' in window){observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){mount();observer?.disconnect();}},{rootMargin:'200px'});observer.observe(root);}else mount();configureDirections(p);}
 function showEvent(e:EventData,url:string,preview=false){invalidateView();setText('address-copy-status','');$('address-manual-copy').hidden=true;lastRenderKey='';copyEpoch++;disposeEffects();document.querySelector('.theme-page')?.classList.add('viewing-event');document.querySelector('.theme-page')?.classList.remove('viewing-error');disposeClock();disposeMap();observer?.disconnect();active=e;const shared=new URL(url);shared.pathname=localizedPath(shared.pathname,currentLocale(),base);activeURL=shared.href;slug=value('theme')||slug;applyTheme();$('creator').hidden=true;$('event-error').hidden=true;$('event-view').hidden=false;$('preview-label').hidden=!preview;$('back-preview').hidden=!preview;$('event-actions').hidden=preview;const ad=app.querySelector<HTMLElement>('.ad-slot');const adMode=import.meta.env.DEV?import.meta.env.PUBLIC_AD_TEST_MODE:undefined;if(ad)void loadAd(ad,preview?'preview':'event',['filled','no-fill','error'].includes(adMode??'')?testAdAdapter(adMode as 'filled'|'no-fill'|'error'):undefined);setText('event-title',e.title);setText('event-date',`${formatEventDate(e.endAt,e.timeZone)} · ${e.timeZone}`);setText('event-organizer',e.organizer?tr(`Anfitrião / organização: ${e.organizer}`):'');setText('event-venue',e.venue??'');setText('event-address',e.address??'');$('copy-address').hidden=!e.address;setText('event-message',e.message);$('event-location').hidden=!(e.venue||e.address);$('display-map').replaceChildren();$('display-map').hidden=!e.location;$('directions').hidden=!e.location;$('legacy-controls').hidden=true;$('legacy-location').hidden=!!e.location||!(e.venue||e.address);$('resolve-location').hidden=$('legacy-location').hidden;transientPoint=e.location;if(e.location)showMap(e.location);const meeting=$<HTMLAnchorElement>('meeting-link');meeting.hidden=!e.meetingUrl;if(e.meetingUrl){meeting.href=e.meetingUrl;meeting.textContent=tr(`Entrar na reunião · ${new URL(e.meetingUrl).hostname}`);} setText('calendar-summary',[e.title,`${formatEventDate(e.endAt,e.timeZone)} · ${e.timeZone}`,e.venue,e.address].filter(Boolean).join('\n'));setText('calendar-duration',e.calendarEndsAt?`Término: ${formatEventDate(e.calendarEndsAt,e.timeZone)}`:'Duração não definida.');$('manual-copy').hidden=true;setText('action-status','');setText('copy-status','');$('copy-link').textContent=tr('Copiar link');const t=themes.find(t=>t.slug===slug)!;disposeClock=mountFlipCountdown($('countdown'),e.endAt,t.ending.message);if(!preview)disposeEffects=mountCelebration(app,()=>false);$('event-title').tabIndex=-1;$('event-title').focus();}
 async function copy(text:string,method:string){const epoch=++copyEpoch;const status=method==='address'?'address-copy-status':'copy-status';const manual=method==='address'?'address-manual-copy':'manual-copy';setText(status,'');$(manual).hidden=true;if(method!=='address')$('copy-link').textContent=tr('Copiar link');emit('share_attempt',slug,method);const copied=await copyText(text);if(epoch!==copyEpoch)return;if(copied){setText(status,method==='address'?'Endereço copiado!':'Mensagem e link copiados!');if(method!=='address')$('copy-link').textContent=tr('Mensagem e link copiados!');$(manual).hidden=true;emit('share_completed',slug,method);}else{setText(status,'Não foi possível copiar automaticamente. Selecione e copie o texto abaixo.');if(method!=='address')$('copy-link').textContent=tr('Copiar link');const fallback=$(manual);fallback.hidden=false;const area=fallback.querySelector('textarea')!;area.value=text;area.focus();area.select();}}

 form.addEventListener('input',event=>{const name=(event.target as HTMLInputElement).name;if(['venue','address','lat','lon'].includes(name))confirmed=undefined;if(['venue','address'].includes(name)){searchEpoch++;$('location-results').replaceChildren();}updateFields();if(name!=='theme')saveDraft();});form.addEventListener('change',event=>{if((event.target as HTMLInputElement).name==='theme'){slug=value('theme');applyTheme();try{suggestDate();}catch(error){errors(error);}let event:EventData|undefined;try{event=readEvent();}catch{}creatorState(formMode==='simple'?'simples':'completo',event);}});
 form.addEventListener('submit',event=>{event.preventDefault();try{clearErrors();const e=readEvent();const url=eventURL(e,pageURL(slug));discardAdvanced();saveDraft();history.pushState({ui:'evento'},'',new URL(url).pathname+new URL(url).hash);emit('event_created',slug);showEvent(e,url);}catch(error){errors(error);}});
 $('preview-event').onclick=()=>{try{clearErrors();const e=readEvent();const url=eventURL(e,pageURL(slug));discardAdvanced();saveDraft();const target=uiURL('previa',e);history.pushState({draft:draft(),returnURL:location.href},'',target.pathname+target.search+target.hash);showEvent(e,url,true);}catch(error){errors(error);}};
 $('back-preview').onclick=()=>{if(history.state?.returnURL)history.back();else if(active){fill(active,slug);creatorState('editar',active);}};$('confirm-location').onclick=()=>{try{confirmed=pointFromInputs();updateFields();saveDraft();}catch(error){errors(error);}};
 $('show-map').onclick=()=>{try{const p=value('lat')&&value('lon')?pointFromInputs():{lat:0,lon:0};const root=$('creator-map');root.hidden=false;const pick=(chosen:Point)=>{set('lat',String(chosen.lat));set('lon',String(chosen.lon));confirmed=undefined;disposeCreatorMap();disposeCreatorMap=renderMap(root,chosen,pick,Number(value('mapZoom'))||3);updateFields();saveDraft();};disposeCreatorMap();disposeCreatorMap=renderMap(root,p,pick,Number(value('mapZoom'))||3);}catch(error){errors(error);}};
 $('search-provider').textContent=tr('Ao buscar, o endereço será enviado ao serviço de localização. Escolha um resultado e confirme o ponto no mapa.');
 $('search-location').onclick=async()=>{const root=$('location-results');root.replaceChildren();root.textContent=tr('Buscando endereço…');const query=[value('venue'),value('address')].filter(Boolean).join(', ');const epoch=++searchEpoch;const view=viewEpoch;const current=()=>epoch===searchEpoch&&view===viewEpoch&&!$('creator').hidden&&query===[value('venue'),value('address')].filter(Boolean).join(', ');try{const choices=await searchLocation(query);if(!current())return;root.replaceChildren();if(!choices.length)root.textContent=tr('Nenhum resultado. Use seleção manual.');for(const choice of choices){const button=document.createElement('button');button.type='button';button.textContent=choice.label;button.onclick=()=>{if(!current())return;set('lat',String(choice.point.lat));set('lon',String(choice.point.lon));set('mapZoom','15');confirmed=undefined;$('show-map').click();updateFields();saveDraft();};root.append(button);}}catch(error){if(current())root.textContent=tr((error as Error).message);}};

 $('recover-event').onclick=()=>{creatorState(formMode==='simple'?'simples':'completo');};
 $('duplicate-event').onclick=()=>{if(active){emit('create_from_event',slug);fill(active,slug);creatorState('editar',active);}};
 $('new-event').onclick=()=>{emit('create_from_event',slug);form.reset();setMode('simple');set('theme',slug);confirmed=undefined;set('time','00:00');set('timeZone',Intl.DateTimeFormat().resolvedOptions().timeZone||'America/Sao_Paulo');suggestDate();showCreator();updateFields();creatorState('simples');};
 $('copy-link').onclick=()=>active?copy(invitation(active,activeURL),'link'):undefined;$('copy-address').onclick=()=>active?.address?copy(active.address,'address'):undefined;
 $('share-event').onclick=async()=>{if(!active)return;const event=active;const url=activeURL;const epoch=viewEpoch;emit('share_attempt',slug,'native');const result=await nativeShare(event,url);if(epoch!==viewEpoch)return;if(result==='shared'){setText('action-status','Compartilhamento concluído no dispositivo.');emit('share_completed',slug,'native');}else if(result==='cancelled')setText('action-status','Compartilhamento cancelado.');else await copy(invitation(event,url),'link');};
 $('download-ics').onclick=async()=>{if(!active)return;try{await downloadCalendar(active,activeURL);emit('calendar_action',slug,'ics');setText('action-status','Arquivo preparado. Confirme a importação no seu calendário.');}catch{setText('action-status','Não foi possível preparar o arquivo. Tente novamente.');}};
 $('current-origin').onclick=async()=>{if(!transientPoint)return;const destination={...transientPoint};const epoch=viewEpoch;const popup=window.open('about:blank','_blank');pendingPopup=popup;if(popup)popup.opener=null;try{const origin=await currentPosition();if(epoch!==viewEpoch){popup?.close();return;}const url=directionsURL(destination,origin);if(popup)popup.location.href=url;else{setText('directions-status','A origem foi obtida. Abra o planejador pelo link.');$<HTMLAnchorElement>('manual-origin').href=url;}}catch(error){popup?.close();if(epoch===viewEpoch)setText('directions-status',(error as Error).message);}finally{if(pendingPopup===popup)pendingPopup=null;}};

 $('resolve-location').onclick=()=>{$('legacy-controls').hidden=false;};$('legacy-confirm').onclick=()=>{try{const lat=$<HTMLInputElement>('legacy-lat').value;const lon=$<HTMLInputElement>('legacy-lon').value;if(!lat||!lon)throw new Error('Informe as duas coordenadas.');const p=validatePoint({lat:Number(lat),lon:Number(lon)});showMap(p);$('legacy-controls').hidden=true;}catch(error){setText('action-status',(error as Error).message);}};
 $('simple-mode').onclick=()=>changeMode('simple');$('complete-mode').onclick=()=>changeMode('complete');set('timeZone',Intl.DateTimeFormat().resolvedOptions().timeZone||'America/Sao_Paulo');set('time','00:00');setMode('simple');applyTheme();suggestDate();updateFields();
 function readLocation(){const renderKey=location.href+JSON.stringify(history.state??null);if(renderKey===lastRenderKey)return;try{const url=new URL(location.href);const ui=url.searchParams.get('ui');if(url.search&&(url.searchParams.size!==1||!['simples','completo','editar','previa','erro'].includes(ui??'')))throw new Error('Estado de navegação inválido.');const route=themes.find(t=>url.pathname===new URL(pageURL(t.slug)).pathname||url.pathname===`${base}${t.slug}/`);if(!route)throw new Error('Tema inválido.');slug=route.slug;set('theme',slug);const canonical=new URL(url);canonical.search='';const saved=history.state?.draft as ReturnType<typeof draft>|undefined;
 if(ui==='erro')throw new Error('Não foi possível abrir este contador. Volte ou crie outro.');
 if(ui==='simples'||ui==='completo'||ui==='editar'||(!url.hash&&!ui)){if(url.hash){const decoded=decodeURL(canonical.href,canonical.href,base,production);fill(decoded.event,decoded.slug);}else{applyTheme();showCreator();setMode(ui==='completo'||ui==='editar'?'complete':'simple');}if(saved)restoreDraft(saved);else setMode(ui==='completo'||ui==='editar'?'complete':'simple');updateFields();if(!ui){const target=uiURL('simples');history.replaceState({draft:draft()},'',target.pathname+target.search);}return;}
 const decoded=decodeURL(canonical.href,canonical.href,base,production);slug=decoded.slug;set('theme',slug);if(ui==='previa'){fill(decoded.event,slug);if(saved)restoreDraft(saved);showEvent(decoded.event,canonical.href,true);}else{showEvent(decoded.event,canonical.href);if(lastOpenedURL!==canonical.href){lastOpenedURL=canonical.href;emit('event_opened',slug);}}
 }catch(error){invalidateView();copyEpoch++;disposeClock();disposeMap();disposeEffects();observer?.disconnect();const ad=app.querySelector<HTMLElement>('.ad-slot');if(ad)void loadAd(ad,'error');document.querySelector('.theme-page')?.classList.add('viewing-error');$('creator').hidden=true;$('event-view').hidden=true;$('event-error').hidden=false;setText('decode-error',(error as Error).message);const target=new URL(location.href);target.search='';target.searchParams.set('ui','erro');history.replaceState(history.state,'',target.pathname+target.search+target.hash);}finally{lastRenderKey=location.href+JSON.stringify(history.state??null);}}

 window.addEventListener('popstate',readLocation);window.addEventListener('hashchange',readLocation);readLocation();
}
