import {validatePoint,type Point} from './event-validation';
export const mapConfig={tiles:import.meta.env.PUBLIC_MAP_TILES||'https://tile.openstreetmap.org/{z}/{x}/{y}.png',search:import.meta.env.PUBLIC_GEOCODER_URL||'', attribution:'© OpenStreetMap contributors'};
export function renderMap(root:HTMLElement,point:Point,onPick?:(point:Point)=>void,zoom=13):()=>void {
 const p=validatePoint(point);root.replaceChildren();root.classList.add('event-map');const z=Math.max(1,Math.min(18,Math.round(zoom)));const n=2**z;const lat=Math.max(-85.05112878,Math.min(85.05112878,p.lat));const x=(p.lon+180)/360*n;const y=(1-Math.asinh(Math.tan(lat*Math.PI/180))/Math.PI)/2*n;const grid=document.createElement('div');grid.className='map-tiles';
 const state=document.createElement('p');state.className='map-state';state.textContent='Carregando mapa…';let loaded=0;let failed=false;
 for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const img=document.createElement('img');img.alt='';img.width=256;img.height=256;img.style.left=`${dx*256+(root.clientWidth||256)/2-(x%1)*256}px`;img.style.top=`${dy*256+160-(y%1)*256}px`;img.src=mapConfig.tiles.replace('{z}',String(z)).replace('{x}',String((Math.floor(x)+dx+n)%n)).replace('{y}',String(Math.max(0,Math.min(n-1,Math.floor(y)+dy))));img.onload=()=>{if(++loaded===9&&!failed)state.textContent='';};img.onerror=()=>{failed=true;state.textContent='Mapa indisponível. Use coordenadas, endereço ou o planejador.';};grid.append(img);}
 const marker=document.createElement('span');marker.className='map-marker';marker.textContent='●';marker.setAttribute('aria-label',`Destino: ${p.lat}, ${p.lon}`);const attribution=document.createElement('a');attribution.href='https://www.openstreetmap.org/copyright';attribution.target='_blank';attribution.rel='noopener noreferrer';attribution.className='map-attribution';attribution.textContent=mapConfig.attribution;root.append(grid,marker,state,attribution);
 if(onPick){root.tabIndex=0;root.setAttribute('aria-label','Selecionar ponto no mapa. Use também os campos latitude e longitude.');const click=(event:MouseEvent)=>{if((event.target as HTMLElement).closest('a'))return;const rect=root.getBoundingClientRect();const px=x+(event.clientX-rect.left-rect.width/2)/256;const py=y+(event.clientY-rect.top-160)/256;onPick(validatePoint({lat:Math.atan(Math.sinh(Math.PI*(1-2*py/n)))*180/Math.PI,lon:((px/n*360)%360+360)%360-180}));};const keydown=(event:KeyboardEvent)=>{const steps:Record<string,[number,number]>={ArrowUp:[1,0],ArrowDown:[-1,0],ArrowLeft:[0,-1],ArrowRight:[0,1]};const delta=steps[event.key];if(!delta)return;event.preventDefault();const step=360/n/4;onPick(validatePoint({lat:Math.max(-90,Math.min(90,p.lat+delta[0]*step)),lon:Math.max(-180,Math.min(180,p.lon+delta[1]*step))}));};root.addEventListener('click',click);root.addEventListener('keydown',keydown);return()=>{root.removeEventListener('click',click);root.removeEventListener('keydown',keydown);};}return()=>{};
}
export async function searchLocation(query:string):Promise<{label:string;point:Point}[]> {if(!mapConfig.search)throw new Error('Busca não configurada. Marque no mapa ou informe coordenadas.');const url=new URL(mapConfig.search);url.searchParams.set('q',query);const response=await fetch(url,{referrerPolicy:'no-referrer'});if(!response.ok)throw new Error('Busca indisponível. Use seleção manual.');const data=await response.json();if(!Array.isArray(data))throw new Error('Resposta inválida.');return data.slice(0,10).map(r=>({label:String(r.display_name??r.label??''),point:validatePoint({lat:Number(r.lat),lon:Number(r.lon)})}));}
