import test from 'node:test';import assert from 'node:assert/strict';import {parseHTML} from 'linkedom';import {readFile} from 'node:fs/promises';import {moduleTS} from './fixtures/load-ts.mjs';
const {invitation}=await moduleTS('src/lib/share.ts');
const {initEventApp}=await moduleTS('src/lib/event-client.ts');const {eventURL,decodeURL}=await moduleTS('src/lib/event-codec.ts');const {themes}=await moduleTS('src/data/themes.ts');const base=process.env.BASE_PATH??'/';
const source={title:'João 🎉',endAt:'2027-06-12T21:00:00.000Z',timeZone:'America/Sao_Paulo',message:'<script>alert(1)</script>',organizer:'Nós',venue:'Salão',address:'Rua 1\nCidade',location:{lat:0,lon:0},calendarEndsAt:'2027-06-12T22:00:00.000Z',meetingUrl:'https://example.test/reuniao?token=teste'};
async function environment(slug,hash='',initialState=null){const selectedSlug=slug.split('/').at(-1);const html=await readFile(`dist/${slug}/index.html`,'utf8');const {window,document}=parseHTML(html);const origin='https://example.test';let url=new URL(`${origin}${base}${slug}/${hash}`);const loc={get href(){return url.href},set href(v){url=new URL(v,url)},get hash(){return url.hash},get pathname(){return url.pathname},origin};window.location=loc;let stack=[{url:url.href,state:initialState}],position=0;const history={get state(){return stack[position].state},get length(){return stack.length},pushState(state,__,v){url=new URL(v,url);stack=stack.slice(0,position+1);stack.push({url:url.href,state:structuredClone(state)});position++;},replaceState(state,__,v){url=new URL(v,url);stack[position]={url:url.href,state:structuredClone(state)};},back(){if(position){position--;url=new URL(stack[position].url);window.dispatchEvent(new window.Event('popstate'));window.dispatchEvent(new window.Event('hashchange'));}},forward(){if(position<stack.length-1){position++;url=new URL(stack[position].url);window.dispatchEvent(new window.Event('popstate'));window.dispatchEvent(new window.Event('hashchange'));}}};window.history=history;window.matchMedia=()=>({matches:true});window.open=()=>({opener:null,location:{href:''},close(){}});window.IntersectionObserver=class{observe(){}disconnect(){}};
 const forms=document.querySelectorAll('form');for(const form of forms){const fields=()=>[...form.querySelectorAll('input,textarea,select')];Object.defineProperty(form,'elements',{value:{namedItem(name){return fields().find(x=>x.getAttribute('name')===name);}}});form.reset=()=>fields().forEach(field=>{if(field.tagName==='SELECT')field.value=selectedSlug;else field.value='';});for(const field of fields())if(field.tagName==='SELECT'){let val=selectedSlug;Object.defineProperty(field,'value',{get(){return val},set(v){val=v},configurable:true});}}
 for(const element of document.querySelectorAll('*')){element.focus=()=>{document._active=element;};if(element.tagName==='TEXTAREA')element.select=()=>{};}
 let requests=0;let intervals=new Set();const nativeSet=globalThis.setInterval;const nativeClear=globalThis.clearInterval;Object.assign(globalThis,{Element:window.Element,HTMLElement:window.HTMLElement,requestAnimationFrame:(fn)=>setTimeout(()=>fn(Date.now()),0),cancelAnimationFrame:clearTimeout,window,document,location:loc,history,IntersectionObserver:window.IntersectionObserver,fetch(){requests++;throw new Error('Unexpected fetch');}});Object.defineProperty(globalThis,'navigator',{value:{},configurable:true});globalThis.setInterval=(...args)=>{const id=nativeSet(...args);intervals.add(id);return id;};globalThis.clearInterval=id=>{intervals.delete(id);nativeClear(id);};
 return {document,window,loc,history,set(name,v){document.getElementById('event-form').elements.namedItem(name).value=v;},get(name){return document.getElementById('event-form').elements.namedItem(name).value;},click(id){const el=document.getElementById(id);if(el.onclick)return el.onclick({target:el});el.dispatchEvent(new window.Event('click'));},input(name,v){this.set(name,v);const field=document.getElementById('event-form').elements.namedItem(name);field.dispatchEvent(new window.Event('input',{bubbles:true}));},submit(){document.getElementById('event-form').dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true}));},get requests(){return requests;},cleanup(){for(const id of intervals)nativeClear(id);globalThis.setInterval=nativeSet;globalThis.clearInterval=nativeClear;}};}
for(const theme of themes)test(`integrated ${theme.slug}: clean open → duplicate → preview → new link`,async()=>{const original=eventURL(source,`https://example.test${base}${theme.slug}/`);const env=await environment(theme.slug,new URL(original).hash);try{initEventApp();assert.equal(env.document.getElementById('event-title').textContent,source.title);const core=env.document.querySelector('.event-art-content');assert.deepEqual([...core.children].map(x=>x.id),['event-title','countdown']);assert.equal(core.querySelector('[data-clock-status]'),null);assert.equal(env.document.getElementById('disable-animation'),null);assert.equal(env.document.getElementById('invite-details'),null);assert.equal(env.document.getElementById('invitation-preview'),null);assert.ok(env.document.getElementById('download-ics').closest('.calendar-card'));assert.equal(env.document.getElementById('event-message').textContent,source.message);assert.equal(env.document.querySelectorAll('#event-message script').length,0);assert.equal(env.document.getElementById('creator').hidden,true);assert.equal(env.document.getElementById('meeting-link').href,source.meetingUrl);env.click('duplicate-event');assert.equal(env.get('address'),source.address);assert.equal(env.get('meetingUrl'),source.meetingUrl);assert.equal(env.get('endDate'),'2027-06-12');assert.equal(env.get('endTime'),'19:00');env.input('title','Cópia de outra pessoa');env.click('preview-event');assert.equal(env.document.getElementById('preview-label').hidden,false);assert.equal(env.document.getElementById('event-actions').hidden,true);env.click('back-preview');env.submit();const copy=decodeURL(env.loc.href,env.loc.href,base).event;assert.equal(copy.title,'Cópia de outra pessoa');assert.deepEqual(copy.location,{lat:0,lon:0});assert.equal(decodeURL(original,original,base).event.title,source.title);assert.equal(env.requests,0);}finally{env.cleanup();}});
test('opened event duplication, local edits reconfirm and switching theme keeps optionals',async()=>{const original=eventURL(source,`https://example.test${base}aniversario/`);const env=await environment('aniversario',new URL(original).hash);try{initEventApp();assert.equal(env.document.querySelector('.import-event'),null);env.click('duplicate-event');assert.equal(env.get('venue'),source.venue);env.input('address','Novo endereço');env.submit();assert.equal(env.document.getElementById('form-errors').hidden,false);assert.equal(env.get('address'),'Novo endereço');env.click('confirm-location');env.set('theme','casamento');env.document.getElementById('event-form').elements.namedItem('theme').dispatchEvent(new env.window.Event('change',{bubbles:true}));env.submit();assert.equal(new URL(env.loc.href).pathname,`${base}pt-br/casamento/`);assert.equal(decodeURL(env.loc.href,env.loc.href,base).event.meetingUrl,source.meetingUrl);assert.equal(env.requests,0);}finally{env.cleanup();}});
test('malformed link is recoverable and contains no raw payload; no local produces no map',async()=>{const env=await environment('aniversario','#v=2&dados=raw-secret');try{initEventApp();assert.equal(env.document.getElementById('event-error').hidden,false);assert.ok(!env.document.getElementById('decode-error').textContent.includes('raw-secret'));env.click('recover-event');assert.equal(env.document.getElementById('creator').hidden,false);env.set('title','Online');env.set('date','2027-06-12');env.set('time','18:00');env.set('timeZone','America/Sao_Paulo');env.submit();assert.equal(env.document.getElementById('event-location').hidden,true);assert.equal(env.requests,0);}finally{env.cleanup();}});
test('simple mode uses browser midnight and switching modes preserves complete fields',async()=>{const env=await environment('aniversario');try{initEventApp();assert.equal(env.document.getElementById('simple-mode').getAttribute('aria-pressed'),'true');env.click('complete-mode');env.set('time','18:30');env.set('message','Uma mensagem preservada');env.set('timeZone','America/Sao_Paulo');env.click('simple-mode');assert.equal(env.get('time'),'18:30');env.click('complete-mode');assert.equal(env.get('message'),'Uma mensagem preservada');assert.equal(env.get('timeZone'),'America/Sao_Paulo');env.click('simple-mode');env.set('title','Modo simples');env.set('date','2027-06-12');env.submit();const event=decodeURL(env.loc.href,env.loc.href,base).event;const zone=Intl.DateTimeFormat().resolvedOptions().timeZone;assert.equal(event.timeZone,zone);const formatted=new Intl.DateTimeFormat('en-GB',{timeZone:zone,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(event.endAt));assert.equal(formatted,'00:00');assert.equal(event.message,'');assert.equal(env.get('message'),'');env.click('duplicate-event');assert.equal(env.document.getElementById('complete-mode').getAttribute('aria-pressed'),'true');}finally{env.cleanup();}});
test('fixed theme suggestions apply on selection, but duplication keeps the original date',async()=>{const original=eventURL({...source,endAt:'2027-06-12T21:00:00.000Z'},`https://example.test${base}natal/`);const env=await environment('natal',new URL(original).hash);try{initEventApp();env.click('duplicate-event');assert.equal(env.get('date'),'2027-06-12');assert.equal(env.get('time'),'18:00');env.set('theme','ano-novo');env.document.getElementById('event-form').elements.namedItem('theme').dispatchEvent(new env.window.Event('change',{bubbles:true}));assert.match(env.get('date'),/^\d{4}-01-01$/);assert.equal(env.get('time'),'00:00');env.set('date','2027-02-14');env.set('theme','casamento');env.document.getElementById('event-form').elements.namedItem('theme').dispatchEvent(new env.window.Event('change',{bubbles:true}));assert.equal(env.get('date'),'2027-02-14');}finally{env.cleanup();}});

test('copy link awaits clipboard success then shows adjacent feedback; failure provides adjacent fallback',async()=>{const url=eventURL(source,`https://example.test${base}aniversario/`);const env=await environment('aniversario',new URL(url).hash);try{initEventApp();assert.equal(env.document.getElementById('copy-invitation'),null);let resolve;globalThis.navigator.clipboard={writeText:()=>new Promise(done=>resolve=done)};const pending=env.click('copy-link');assert.equal(env.document.getElementById('copy-link').textContent,'Copiar link');assert.equal(env.document.getElementById('copy-status').hidden,true);resolve();await pending;assert.equal(env.document.getElementById('copy-link').textContent,'Mensagem e link copiados!');assert.equal(env.document.getElementById('copy-status').textContent,'Mensagem e link copiados!');assert.ok(env.document.getElementById('copy-status').closest('.share-actions'));globalThis.navigator.clipboard={writeText:async()=>{throw new Error('denied')}};await env.click('copy-link');assert.match(env.document.getElementById('copy-status').textContent,/Não foi possível/);const fallback=env.document.getElementById('manual-copy');assert.equal(fallback.hidden,false);assert.ok(fallback.closest('.share-actions'));assert.equal(fallback.querySelector('textarea').value,invitation(source,url.replace(`${base}aniversario/`,`${base}pt-br/aniversario/`)));globalThis.navigator.clipboard={writeText:()=>new Promise(done=>resolve=done)};const late=env.click('copy-link');env.click('duplicate-event');resolve();await late;assert.equal(env.document.getElementById('copy-status').hidden,true);assert.equal(fallback.hidden,true);}finally{env.cleanup();}});
test('history back/forward restores event, duplicate drafts, preview and theme without duplicate mounts',async()=>{const original=eventURL(source,`https://example.test${base}aniversario/`);const env=await environment('aniversario',new URL(original).hash);try{initEventApp();env.click('duplicate-event');assert.equal(new URL(env.loc.href).search,'?ui=editar');env.input('title','Outra história');env.click('preview-event');const previewURL=env.loc.href;assert.equal(new URL(previewURL).search,'?ui=previa');assert.throws(()=>decodeURL(previewURL,previewURL,base));env.history.back();assert.equal(env.get('title'),'Outra história');assert.equal(env.document.getElementById('creator').hidden,false);env.history.back();assert.equal(env.loc.href,original);assert.equal(env.document.getElementById('event-title').textContent,source.title);let mounted;env.window.addEventListener('popstate',()=>{mounted=env.document.querySelector('.flip-clock')});env.window.addEventListener('hashchange',()=>{assert.equal(env.document.querySelector('.flip-clock'),mounted)});env.history.forward();assert.equal(env.get('title'),'Outra história');env.history.forward();assert.equal(env.document.getElementById('preview-label').hidden,false);assert.equal(env.document.getElementById('event-title').textContent,'Outra história');env.history.back();env.set('theme','casamento');env.document.getElementById('event-form').elements.namedItem('theme').dispatchEvent(new env.window.Event('change',{bubbles:true}));assert.equal(new URL(env.loc.href).pathname,`${base}pt-br/casamento/`);env.history.back();assert.equal(env.get('theme'),'aniversario');assert.equal(env.get('address'),source.address);env.submit();assert.equal(new URL(env.loc.href).search,'');assert.equal(decodeURL(env.loc.href,env.loc.href,base).event.title,'Outra história');env.history.back();assert.equal(env.document.getElementById('creator').hidden,false);assert.equal(decodeURL(original,original,base).event.title,source.title);}finally{env.cleanup()}});
test('direct edit/preview URLs restore their payload; reload restores incomplete draft history state',async()=>{const url=new URL(eventURL(source,`https://example.test${base}natal/`));url.search='?ui=editar';let env=await environment('natal',url.search+url.hash);let incompleteURL,saved;try{initEventApp();assert.equal(env.get('date'),'2027-06-12');assert.equal(env.get('time'),'18:00');env.input('title','x'.repeat(84));env.click('simple-mode');assert.equal(new URL(env.loc.href).search,'?ui=simples');env.history.back();assert.equal(env.get('title'),'x'.repeat(84));assert.equal(env.document.getElementById('complete-mode').getAttribute('aria-pressed'),'true');incompleteURL=new URL(env.loc.href);saved=env.history.state;}finally{env.cleanup()}env=await environment('natal',incompleteURL.search+incompleteURL.hash,saved);try{initEventApp();assert.equal(env.get('title'),'x'.repeat(84));assert.equal(env.get('address'),source.address);env.submit();assert.equal(env.document.getElementById('form-errors').hidden,false);}finally{env.cleanup()}url.search='?ui=previa';env=await environment('natal',url.search+url.hash);try{initEventApp();assert.equal(env.document.getElementById('preview-label').hidden,false);assert.equal(env.document.getElementById('event-title').textContent,source.title);env.click('back-preview');assert.equal(new URL(env.loc.href).search,'?ui=editar');assert.equal(env.get('meetingUrl'),source.meetingUrl);}finally{env.cleanup()}});
test('unknown UI query fails safely and recovery participates in history',async()=>{const env=await environment('aniversario','?ui=inventado#v=2&dados=private');try{initEventApp();assert.equal(new URL(env.loc.href).search,'?ui=erro');assert.equal(env.document.getElementById('event-error').hidden,false);env.click('recover-event');assert.equal(new URL(env.loc.href).search,'?ui=simples');env.input('title','Draft recuperado');env.history.back();assert.equal(env.document.getElementById('event-error').hidden,false);env.history.forward();assert.equal(env.get('title'),'Draft recuperado');}finally{env.cleanup()}});

test('skip link focuses main while preserving event fragment, active countdown and native no-JS fallback',async()=>{const url=eventURL(source,`https://example.test${base}aniversario/`);const env=await environment('aniversario',new URL(url).hash);try{initEventApp();const {initSkipLink}=await moduleTS('src/lib/skip-link.ts');const main=env.document.getElementById('conteudo');let scrolled=false;main.scrollIntoView=()=>{scrolled=true};initSkipLink();const link=env.document.querySelector('.skip-link');assert.equal(link.getAttribute('href'),'#conteudo');assert.equal(main.getAttribute('tabindex'),'-1');const clock=env.document.querySelector('.flip-clock');const click=new env.window.Event('click',{bubbles:true,cancelable:true});link.dispatchEvent(click);assert.equal(click.defaultPrevented,true);assert.equal(env.loc.href,url);assert.equal(env.document._active,main);assert.equal(scrolled,true);assert.equal(env.document.querySelector('.flip-clock'),clock);assert.equal(env.document.getElementById('event-error').hidden,true);}finally{env.cleanup()}});
test('simple preview and generation discard advanced fields only after valid submission',async()=>{for(const action of ['preview','generate']){const url=eventURL(source,`https://example.test${base}aniversario/`);const env=await environment('aniversario',new URL(url).hash);try{initEventApp();env.click('duplicate-event');env.click('simple-mode');env.input('title','');if(action==='preview')env.click('preview-event');else env.submit();assert.equal(env.get('message'),source.message);assert.equal(env.get('address'),source.address);env.input('title','Somente o essencial');if(action==='preview')env.click('preview-event');else env.submit();const canonical=new URL(env.loc.href);canonical.search='';const event=decodeURL(canonical.href,canonical.href,base).event;assert.deepEqual(Object.keys(event).sort(),['endAt','message','timeZone','title']);assert.equal(event.message,'');assert.equal(event.timeZone,Intl.DateTimeFormat().resolvedOptions().timeZone);for(const name of ['message','organizer','venue','address','meetingUrl','endDate','endTime','lat','lon'])assert.equal(env.get(name),'',name);assert.equal(env.document.getElementById('event-location').hidden,true);env.history.back();env.click('complete-mode');assert.equal(env.get('message'),'');assert.equal(env.get('address'),'');}finally{env.cleanup()}}});
test('map selections persist unconfirmed coordinates and creator map is disposed across views',async()=>{const env=await environment('aniversario');try{initEventApp();env.click('complete-mode');env.input('venue','Praça');env.click('show-map');const root=env.document.getElementById('creator-map');root.getBoundingClientRect=()=>({left:0,top:0,width:256,height:320});Object.defineProperty(root,'clientWidth',{value:256});const key=new env.window.Event('keydown');key.key='ArrowRight';root.dispatchEvent(key);const lon=env.get('lon');assert.ok(Number(lon)>0);assert.equal(env.history.state.draft.confirmed,undefined);assert.equal(env.history.state.draft.values.lon,lon);env.click('simple-mode');assert.equal(root.children.length,0);env.history.back();assert.equal(env.get('lon'),lon);assert.equal(env.history.state.draft.confirmed,undefined);const old=env.get('lon');root.dispatchEvent(key);assert.equal(env.get('lon'),old);env.input('venue','');assert.equal(root.children.length,0);assert.equal(env.get('lon'),'');}finally{env.cleanup()}});
test('configured searches ignore reversed completion, changed address, stale buttons and navigation',async()=>{process.env.TEST_GEOCODER_URL='https://provider.example/search';const configured=await moduleTS('src/lib/event-client.ts');delete process.env.TEST_GEOCODER_URL;const env=await environment('aniversario');let pending=[];try{globalThis.fetch=url=>new Promise(resolve=>pending.push({url:new URL(url),resolve}));configured.initEventApp();env.click('complete-mode');env.input('venue','Primeiro');const first=env.click('search-location');env.input('venue','Segundo');const second=env.click('search-location');assert.equal(pending[1].url.searchParams.get('q'),'Segundo');pending[1].resolve({ok:true,json:async()=>[{display_name:'Escolha nova',lat:'-23.5',lon:'-46.6'}]});await second;const button=env.document.getElementById('location-results').querySelector('button');pending[0].resolve({ok:true,json:async()=>[{display_name:'Velha',lat:'1',lon:'2'}]});await first;assert.equal(env.document.getElementById('location-results').textContent,'Escolha nova');button.onclick();assert.equal(env.get('lat'),'-23.5');assert.equal(env.history.state.draft.values.lon,'-46.6');assert.equal(env.history.state.draft.confirmed,undefined);env.click('confirm-location');assert.deepEqual(env.history.state.draft.confirmed,{lat:-23.5,lon:-46.6});env.input('address','Mudou');env.input('lat','8');button.onclick();assert.equal(env.get('lat'),'8');assert.equal(env.history.state.draft.confirmed,undefined);const stale=env.click('search-location');env.click('simple-mode');pending[2].resolve({ok:true,json:async()=>[{display_name:'Depois da navegação',lat:'9',lon:'9'}]});await stale;assert.ok(!env.document.getElementById('location-results').textContent.includes('Depois'));}finally{env.cleanup()}});
test('deferred share and geolocation cannot act on a different view',async()=>{const url=eventURL(source,`https://example.test${base}aniversario/`);const env=await environment('aniversario',new URL(url).hash);try{initEventApp();let rejectShare,position;let copied=[];globalThis.navigator.share=()=>new Promise((_,reject)=>rejectShare=reject);globalThis.navigator.clipboard={writeText:async text=>copied.push(text)};const share=env.click('share-event');let closed=false;const popup={opener:null,location:{href:''},close(){closed=true}};env.window.open=()=>popup;globalThis.navigator.geolocation={getCurrentPosition(success){position=success}};const geo=env.click('current-origin');env.click('duplicate-event');assert.equal(closed,true);rejectShare(new Error('unavailable'));position({coords:{latitude:12,longitude:34}});await Promise.all([share,geo]);assert.deepEqual(copied,[]);assert.equal(popup.location.href,'');assert.equal(env.document.getElementById('directions-status').textContent,'');}finally{env.cleanup()}});
test('denied address clipboard in preview shows its fallback outside hidden event actions',async()=>{const url=eventURL(source,`https://example.test${base}aniversario/`);const env=await environment('aniversario',new URL(url).hash);try{initEventApp();env.click('duplicate-event');env.click('preview-event');globalThis.navigator.clipboard={writeText:async()=>{throw new Error('denied')}};await env.click('copy-address');const fallback=env.document.getElementById('address-manual-copy');assert.equal(env.document.getElementById('event-actions').hidden,true);assert.equal(fallback.hidden,false);assert.equal(fallback.closest('#event-actions'),null);assert.equal(fallback.querySelector('textarea').value,source.address);assert.match(env.document.getElementById('address-copy-status').textContent,/Não foi possível/);}finally{env.cleanup()}});
test('rendered calendar button creates Blob URL and clicks a downloadable anchor for active event',async()=>{const {default:ICAL}=await import('ical.js');const url=eventURL(source,`https://example.test${base}aniversario/`);const env=await environment('aniversario',new URL(url).hash);const create=URL.createObjectURL,revoke=URL.revokeObjectURL;try{initEventApp();let blob,clicked;URL.createObjectURL=value=>{blob=value;return 'blob:test-calendar'};URL.revokeObjectURL=()=>{};const original=env.document.createElement.bind(env.document);env.document.createElement=name=>{const node=original(name);if(name==='a')node.click=()=>{clicked={href:node.href,download:node.download}};return node};await env.click('download-ics');assert.deepEqual(clicked,{href:'blob:test-calendar',download:'evento-contagem.ics'});assert.equal(blob.type,'text/calendar;charset=utf-8');const component=new ICAL.Component(ICAL.parse(await blob.text())).getFirstSubcomponent('vevent');assert.equal(component.getFirstPropertyValue('summary'),source.title);assert.equal(component.getFirstPropertyValue('url'),url.replace(`${base}aniversario/`,`${base}pt-br/aniversario/`));assert.equal(component.getFirstPropertyValue('dtstart').toJSDate().toISOString(),source.endAt);assert.equal(component.getFirstPropertyValue('dtend').toJSDate().toISOString(),source.calendarEndsAt);}finally{URL.createObjectURL=create;URL.revokeObjectURL=revoke;env.cleanup()}});

test('copy link uses selection fallback when clipboard API is denied and restores focus',async()=>{const url=eventURL(source,`https://example.test${base}aniversario/`);const env=await environment('aniversario',new URL(url).hash);try{initEventApp();globalThis.navigator.clipboard={writeText:async()=>{throw new Error('denied')}};let copied;const original=env.document.createElement.bind(env.document);env.document.createElement=name=>{const node=original(name);if(name==='textarea'){node.focus=()=>{};node.select=()=>{};node.setSelectionRange=()=>{};}return node};env.document.execCommand=command=>{assert.equal(command,'copy');copied=env.document.body.lastElementChild.value;return true};await env.click('copy-link');assert.equal(copied,invitation(source,url.replace(`${base}aniversario/`,`${base}pt-br/aniversario/`)));assert.equal(env.document.body.lastElementChild.tagName==='TEXTAREA',false);assert.equal(env.document.getElementById('copy-link').textContent,'Mensagem e link copiados!');}finally{env.cleanup()}});

test('English event keeps visitor text, translates controls/errors/dates and shares an English URL',async()=>{
 const env=await environment('en-us/zoeira');try{
  initEventApp();assert.equal(env.document.documentElement.lang,'en-US');
  assert.equal(env.document.getElementById('creator-theme-name').textContent,'Just for laughs');
  env.submit();assert.match(env.document.getElementById('form-errors').textContent,/Choose a valid date/);
  env.set('title','Título');env.set('date','2027-06-12');env.click('complete-mode');env.set('time','18:00');env.set('timeZone','America/New_York');env.set('message','Mensagem');env.submit();
  assert.equal(new URL(env.loc.href).pathname,`${base}en-us/zoeira/`);
  assert.equal(env.document.getElementById('event-title').textContent,'Título');
  assert.equal(env.document.getElementById('event-message').textContent,'Mensagem');
  assert.match(env.document.getElementById('event-date').textContent,/Saturday, June 12, 2027/);
  assert.match(env.document.querySelector('[data-clock-status]').textContent,/remaining/);
  let copied='';navigator.clipboard={writeText:async text=>{copied=text;}};await env.click('copy-link');
  assert.ok(copied.endsWith(env.loc.href));assert.match(copied,/Saturday, June 12, 2027/);assert.ok(copied.includes('Mensagem'));assert.equal(copied.split(env.loc.href).length-1,1);assert.equal(env.document.getElementById('copy-status').textContent,'Message and link copied!');
  env.click('duplicate-event');env.click('preview-event');env.click('back-preview');env.submit();
  assert.equal(new URL(env.loc.href).pathname,`${base}en-us/zoeira/`);
 }finally{env.cleanup();}
});

test('English expired event and malformed link provide English messages',async()=>{
 const expired={...source,endAt:'2020-01-01T00:00:00.000Z'};delete expired.calendarEndsAt;
 const link=eventURL(expired,`https://example.test${base}en-us/evento-politico/`);
 const env=await environment('en-us/evento-politico',new URL(link).hash);try{initEventApp();assert.equal(env.document.querySelector('[data-clock-status]').textContent,'It’s time for our event!');}finally{env.cleanup();}
 const broken=await environment('en-us/zoeira','#v=2&dados=secret');try{initEventApp();assert.equal(broken.document.getElementById('decode-error').textContent,'Invalid link version or data.');}finally{broken.cleanup();}
});

test('copy and native-share fallback use the same invitation with exactly one event link',async()=>{const url=eventURL(source,`https://example.test${base}pt-br/aniversario/`);const env=await environment('pt-br/aniversario',new URL(url).hash);try{initEventApp();let copied,payload;navigator.clipboard={writeText:async text=>{copied=text}};navigator.share=async data=>{payload=data};await env.click('share-event');await env.click('copy-link');assert.equal(copied,payload.text);assert.equal(payload.url,undefined);assert.ok(copied.endsWith(`\n\n${url}`));assert.equal(copied.split(url).length-1,1);assert.ok(copied.includes(source.title));assert.ok(copied.includes(source.address));const expected=copied;navigator.share=undefined;copied='';await env.click('share-event');assert.equal(copied,expected);}finally{env.cleanup()}});
