import test from 'node:test';import assert from 'node:assert/strict';import {parseHTML} from 'linkedom';import {moduleTS} from './fixtures/load-ts.mjs';
const {renderMap,searchLocation,createLocationSearch,mapConfig}=await moduleTS('src/lib/event-map.ts');
test('manual OSM map point/keyboard, explicit tile failure and attribution',()=>{const {document,window}=parseHTML('<html><body><div id="map"></div></body></html>');globalThis.document=document;const root=document.getElementById('map');root.getBoundingClientRect=()=>({left:0,top:0,width:256,height:320});Object.defineProperty(root,'clientWidth',{value:256});let selected=[];const stop=renderMap(root,{lat:0,lon:0},p=>selected.push(p),3);assert.equal(root.querySelectorAll('img').length,9);for(const tile of root.querySelectorAll('img'))assert.equal(tile.getAttribute('referrerpolicy'),'strict-origin');assert.ok(root.querySelector('.map-attribution').textContent.includes('OpenStreetMap'));root.querySelector('img').onerror();assert.equal(root.querySelector('img').hidden,true);assert.match(root.querySelector('.map-state').textContent,/indisponível/);const click=new window.Event('click');Object.assign(click,{clientX:128,clientY:160});root.dispatchEvent(click);assert.deepEqual(selected[0],{lat:0,lon:0});const key=new window.Event('keydown');key.key='ArrowRight';root.dispatchEvent(key);assert.ok(selected[1].lon>0);stop();});
test('Photon is available without configuration and empty input makes no request',async()=>{let calls=0;globalThis.fetch=()=>{calls++;throw new Error();};assert.equal(mapConfig.search,'https://photon.komoot.io/api/');await assert.rejects(searchLocation('  '),/3 caracteres/);assert.equal(calls,0);});
test('configured provider transports query once and converts textual coordinates',async()=>{process.env.TEST_GEOCODER_URL='https://provider.example/search';let calls=[];globalThis.fetch=async(url,options)=>{calls.push({url:new URL(url),options});return {ok:true,json:async()=>[{display_name:'Praça',lat:'-23.5',lon:'-46.6'}]}};try{const configured=await moduleTS('src/lib/event-map.ts');assert.deepEqual(await configured.searchLocation('Praça, São Paulo'),[{label:'Praça',point:{lat:-23.5,lon:-46.6}}]);assert.equal(calls.length,1);assert.equal(calls[0].url.searchParams.get('q'),'Praça, São Paulo');assert.equal(calls[0].options.referrerPolicy,'strict-origin');}finally{delete process.env.TEST_GEOCODER_URL}});

const photonData={type:'FeatureCollection',features:[{type:'Feature',geometry:{type:'Point',coordinates:[-46.657,-23.561]},properties:{name:'MASP',street:'Avenida Paulista',housenumber:'1578',city:'São Paulo',country:'Brasil'}}]};
test('Photon GeoJSON uses lon/lat correctly, coalesces queries, caches and expires',async()=>{
 let now=10000,calls=0,finish;const search=createLocationSearch('https://photon.komoot.io/api/',async(url,options)=>{calls++;assert.equal(url.searchParams.get('limit'),'5');assert.equal(options.referrerPolicy,'strict-origin');return new Promise(resolve=>finish=resolve)},()=>now);
 const first=search(' MASP  São Paulo ');const duplicate=search('masp São Paulo');assert.equal(calls,1);await assert.rejects(search('Outro local'),/Aguarde/);
 finish({ok:true,json:async()=>photonData});const result=await first;assert.deepEqual(await duplicate,result);assert.deepEqual(result[0].point,{lat:-23.561,lon:-46.657});assert.match(result[0].label,/MASP.*Avenida Paulista, 1578.*São Paulo/);
 result[0].point.lat=0;assert.equal((await search('MASP São Paulo'))[0].point.lat,-23.561);assert.equal(calls,1);
 now+=16*60*1000;const expired=search('MASP São Paulo');assert.equal(calls,2);finish({ok:true,json:async()=>photonData});await expired;
});
test('Photon busy and malformed responses remain recoverable without caching failures',async()=>{
 let now=10000,calls=0;const responses=[{ok:false,status:429},{ok:true,json:async()=>({bad:true})},{ok:true,json:async()=>({type:'FeatureCollection',features:[]})}];const search=createLocationSearch('https://photon.komoot.io/api/',async()=>{calls++;return responses.shift()},()=>now);
 await assert.rejects(search('Um endereço'),/30 segundos/);now+=2000;await assert.rejects(search('Um endereço'),/Aguarde/);assert.equal(calls,1);now+=30000;await assert.rejects(search('Um endereço'),/Resposta/);now+=2000;assert.deepEqual(await search('Um endereço'),[]);assert.equal(calls,3);
});
