/** Deterministic raster derivatives of the approved, separately composed PNG originals. */
import sharp from 'sharp';
import {writeFile,readFile,mkdir,readdir,unlink} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const slugs=['aniversario','ano-novo','natal','familia','empresa','formatura-fundamental','formatura-ensino-medio','formatura-faculdade','casamento','viagem','cha-de-bebe','evento-tecnologia','evento-medicina','evento-direito','festa','evento-politico','zoeira','encontro-amigos','jantar'];
const selected=process.argv.slice(2);
if(selected.some(slug=>!slugs.includes(slug)))throw new Error('Use only known theme slugs as arguments.');
const previous=selected.length?JSON.parse(await readFile('public/art/manifest.json','utf8')):null;
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
const manifest={version:2,date:'2026-10-05',generator:'OpenAI built-in image_gen',artFormat:'PNG raster',rights:{origin:'Generated original artwork for Contagem using built-in OpenAI image_gen; no third-party reference art supplied.',license:'No third-party artist license is asserted. Use is subject to applicable OpenAI terms and operator obligations.'},requirements:{inclusive:true,noPeople:true,noEmbeddedText:true,dynamicContent:'HTML only'},exports:{tool:'sharp',version:sharp.versions.sharp,compression:'PNG palette quality100, Floyd-Steinberg dither0.75, effort10, zlib9; no text overlays; OG falls back to palette quality80/dither0.3 if needed for the 500 KB budget',servedMobile:'540x960 responsive PNG, <=600000 bytes; full 1080x1920 export and original preserved but not loaded automatically'},themes:[]};
await mkdir('public/og',{recursive:true});
async function exportPNG(input,target,width,height){const bytes=await sharp(input).resize(width,height,{fit:'fill',kernel:sharp.kernel.lanczos3}).removeAlpha().png({palette:true,quality:100,dither:.75,compressionLevel:9,effort:10}).toBuffer();await writeFile(target,bytes);return {path:target.replace('public/',''),width,height,bytes:bytes.length,sha256:hash(bytes)};}
for(const slug of slugs){if(selected.length&&!selected.includes(slug)){const existing=previous.themes.find(t=>t.slug===slug);if(!existing)throw new Error(`Missing manifest entry for ${slug}; include it in the requested exports.`);manifest.themes.push(existing);continue;}const desktopPath=`public/art/originals/${slug}-desktop.png`;const mobilePath=`public/art/originals/${slug}-mobile.png`;const desktop=await readFile(desktopPath);const mobile=await readFile(mobilePath);const dm=await sharp(desktop).metadata();const mm=await sharp(mobile).metadata();const promptsPath=`public/art/${slug}-generation.json`;const promptRecord=JSON.parse(await readFile(promptsPath,'utf8'));const promptEntries=Array.isArray(promptRecord)?promptRecord:promptRecord.prompts;const outputs={};outputs.desktop=await exportPNG(desktop,`public/art/${slug}-desktop.png`,1920,1080);outputs.mobileFull=await exportPNG(mobile,`public/art/${slug}-mobile-full.png`,1080,1920);
 // A separate high-quality responsive derivative keeps first mobile access below 600 KB.
 for(const width of [540]){const height=Math.round(width*16/9);outputs.mobile=await exportPNG(mobile,`public/art/${slug}-mobile.png`,width,height);if(outputs.mobile.bytes<=600000)break;}if(outputs.mobile.bytes>600000)throw new Error(`${slug}: mobile budget exceeded`);
 outputs.gallery=await exportPNG(desktop,`public/art/${slug}-gallery.png`,640,360);
 // Contain the entire approved desktop composition; solid padding for the slightly taller OG ratio.
 const pixel=await sharp(desktop).resize(1,1).raw().toBuffer();let og;let ogQuality=100;for(const quality of [100,80]){og=await sharp(desktop).resize(1200,630,{fit:'contain',background:{r:pixel[0],g:pixel[1],b:pixel[2]}}).removeAlpha().png({palette:true,quality,dither:quality===100?.75:.3,compressionLevel:9,effort:10}).toBuffer();ogQuality=quality;if(og.length<=500000)break;}if(og.length>500000)throw new Error(`${slug}: OG budget exceeded (${og.length})`);await writeFile(`public/og/${slug}.png`,og);outputs.og={path:`og/${slug}.png`,width:1200,height:630,bytes:og.length,sha256:hash(og),quality:ogQuality};
 manifest.themes.push({slug,review:(!Array.isArray(promptRecord)&&promptRecord.review)||'Gender-inclusive occasion artwork; no people or embedded text. Original-generation visual review performed by the root agent.',originals:[{path:desktopPath.replace('public/',''),width:dm.width,height:dm.height,bytes:desktop.length,sha256:hash(desktop)},{path:mobilePath.replace('public/',''),width:mm.width,height:mm.height,bytes:mobile.length,sha256:hash(mobile)}],promptManifest:promptsPath.replace('public/',''),prompts:promptEntries,outputs});console.log(`${slug}: mobile ${outputs.mobile.bytes} bytes, OG ${og.length} bytes`);
}
await writeFile('public/art/manifest.json',JSON.stringify(manifest,null,2)+'\n');
// Only obsolete generated vector exports in public/art; preserve originals and provenance.
for(const file of await readdir('public/art'))if(file.endsWith('.svg'))await unlink(`public/art/${file}`);
